# Generated by Django 3.0.3 on 2020-05-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='proposals/pdfs')),
            ],
        ),
    ]
