# Generated by Django 3.0.3 on 2020-05-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pol', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pdf',
            field=models.FileField(default='user.pdf', upload_to='props/pdfs'),
        ),
    ]
